//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedicineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int C_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public string ContactNumber { get; set; }
        public byte[] Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
