//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedicineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage
    {
        public int Ma_ID { get; set; }
        public Nullable<int> M_ID { get; set; }
        public Nullable<int> Stk_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual User User { get; set; }
    }
}
