//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedicineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Info
    {
        public int Supply_ID { get; set; }
        public Nullable<int> Sup_ID { get; set; }
        public Nullable<int> M_ID { get; set; }
        public Nullable<decimal> Due_Payment { get; set; }
        public System.DateTime Due_Date { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
